---
pipeline: test-pipeline
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments: cells,cytoplasm,nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  features: infer
annotate:
  perform: true
  well_column: Metadata_Well
  external: 
normalize:
  perform: true
  method: mad_robustize
  features: infer
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: data
plates:
  - name: 218360 
    process: true
  - name: 218360-2
    process: true
process: true
